# Generated by Django 4.1 on 2022-08-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('school_admin_name', models.CharField(max_length=100, null=True)),
                ('school_email', models.EmailField(max_length=254, null=True)),
                ('school_address', models.CharField(max_length=100, null=True, unique=True)),
                ('school_location', models.CharField(max_length=100, null=True)),
                ('school_phone_no', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_first_name', models.CharField(max_length=150, null=True)),
                ('st_last_name', models.CharField(max_length=150, null=True)),
                ('parent_name', models.CharField(max_length=200, null=True)),
                ('parent_email', models.EmailField(max_length=100, null=True)),
                ('parent_phone_no', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Lagos', max_length=100, null=True)),
                ('admission_no', models.CharField(max_length=12, null=True, unique=True)),
                ('fees_owed', models.IntegerField(null=True)),
                ('last_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debtors.school')),
            ],
        ),
    ]
